### ISSUE TITLE
Issue with a model that returns the gradient of a sequence

### ISSUE THREAD

**Issue by raphaelvalentin** [fabiodimarco/tf-levenberg-marquardt#12]
Hi Fabio, 

I am observing an issue with the LM optimizer.
The test case described in the attachment is about a model that returns the gradient of a sequence.
The model is described as following:

```
class NeuralNet(tf.keras.Model):
    def __init__(self, dim):
        super().__init__()
        self.lay1 = Dense(dim[1], activation='softplus')
        self.lay2 = Dense(dim[2], activation='softplus')
        self.lay3 = Dense(dim[3])

    def model_charge(self, x_input, training=False):
        """ model of gate charge
        """
        x = self.lay1(x_input, training=training)
        x = self.lay2(x, training=training)
        x = self.lay3(x, training=training)
        return x

    def call(self, x_input, training=False):
        """ calc gradient from model_charge > dQ/dV = C
        """
        with tf.GradientTape(persistent=True) as tape:
            x_input = tf.convert_to_tensor(x_input)
            tape.watch(x_input)
            x = self.model_charge(x_input, training)
            o_x = tape.gradient(x, x_input)
        return o_x
```

This model is used to fit a capacitance curve (curve fitting) with a charge model (C = dQ/dV). It is required to minimize the gradient. Later, the weight/bias (and derivation of the layers into equations) can be included into a more bigger model (current + charge) such written in a veriloga Spice model file (which requires a charge model as input). The test case works with NADAM but not with LM. This is why I suspect a bug with LM. I admit that GradientTape is tricky and not a usual case.

Python terminates with a ValueError without starting the optimization:

```
    File "...bug/levenberg_marquardt.py", line 400, in _compute_jacobian  *
        jacobians = [tf.reshape(j, (num_residuals, -1)) for j in jacobians]

    ValueError: Tried to convert 'tensor' to a tensor and failed. Error: None values not supported.

```

I would like to use LM because it shows much better optimum than NADAM in consideration of a curve fitting job. In general, I can see at least 2 decades better in RMS.
I have no clue how to solve this issue. Is it possible that you get a look?

Thank you very much for your support !
Raphael.

The test case is described in this file [fit.py.txt](https://github.com/fabiodimarco/tf-levenberg-marquardt/files/8966893/fit.py.txt).

**Comment by raphaelvalentin** [comment]
Maybe I just answer to myself. Need to double check that my addition is okay.

In `levenberg_marquardt.py`

```
def _compute_jacobian(self, inputs, targets):
...
        jacobians = tape.jacobian(
            residuals,
            self.model.trainable_variables,
            experimental_use_pfor=self.experimental_use_pfor, unconnected_gradients=tf.UnconnectedGradients.ZERO)
...
    jacobians = [tf.reshape(j, (num_residuals, -1)) for j in jacobians if j is not None]

```

src: https://stackoverflow.com/questions/57144586/tensorflow-gradienttape-gradients-does-not-exist-for-variables-intermittently

**Comment by fabiodimarco** [comment]
Hi Raphael,

I executed the code you provided, it seems that adding unconnected_gradients=tf.UnconnectedGradients.ZERO does solves the error.
Does it also work as expected?

**Comment by raphaelvalentin** [comment]
Hi Fabio,
yes, it is working perfectly for my case. 
Thanks a lot !
Raphael.
