### ISSUE TITLE
Random results

### ISSUE THREAD

**Issue by advanced-bencoding** [fabiodimarco/tf-levenberg-marquardt#14]
Hello, I get a random result everytime I fit the model with my data. Is there a way to specify seed so that i get the same result with respect to a seed? or does this algorithm just work differently?

**Comment by fabiodimarco** [comment]
Hi, yes you can initialise your model the same way you would initialise a keras model. The training process should be deterministic. Have you checked if the weights are actually initialised equal on each run?
