### ISSUE TITLE
Error when running the code test_curve_fitting.py

### ISSUE THREAD

**Issue by saddamhijazi** [fabiodimarco/tf-levenberg-marquardt#19]
Hello, I would like to thank you for the codes, I am trying to use the LM optimizer in my work and I have encountered an error when I run the test_curve_fitting.py script. The error says the following :

`AttributeError: 'ModelWrapper' object has no attribute '_validate_target_and_loss'`

I am using Tensorflow 2.7.0, could please help me in checking the source of this error, the error pops up after calling the fit method of the model_wrapper. Thank you very much.

**Comment by fabiodimarco** [comment]
Hi @saddamhijazi I am using version 2.10.0 right now and it works. Maybe some of the last changes that I have done are not compatible with older versions of Tensorflow. Is it a problem for you to use a more recent version?

**Comment by saddamhijazi** [comment]
@fabiodimarco Thank you very much for your answer, I have tried the code on Tensorflow 2.11 and it worked. May I ask you if the code could be installed using pip or something ? The way I run it now is just by adding the path of the folder to .bashrc like this:

export PYTHONPATH="${PYTHONPATH}:$HOME/tf-levenberg-marquardt"

**Comment by fabiodimarco** [comment]
@saddamhijazi at the moment it can not be installed using pip install. But actually in the next days I'll find some time do it. I'll let you know when I do the change.

**Comment by saddamhijazi** [comment]
Thank you very much, I will close this issue here and I will open another one which is related to my application of the LM optimizer for physics informed neural networks. Thank you.
