### ISSUE TITLE
Error when using the "fit" function on the wrapped model  "unexpected keyword argument 'count_mode'"

### ISSUE THREAD

**Issue by ashkanee** [fabiodimarco/tf-levenberg-marquardt#21]
I get the following error when using the wrapped function on the "fit" function:

Executing this:
`model_wrapper.fit(train_dataset, epochs=2)`

Results in:
`    callbacks.append(tf.keras.callbacks.ProgbarLogger(
TypeError: __init__() got an unexpected keyword argument 'count_mode'`

I have also tried with the provided examples in this git directory, but get the same error.

This goes away if we set "verbose=0" in the fit function defined in the wrapper class, but I? would like to see if there is any solution.

Can you please help?  

Thanks

**Comment by fabiodimarco** [comment]
Updated to Tensorflow 2.18.0
