### ISSUE TITLE
Error when running the model.fit on the wrapped model "Exception encountered when calling ModelWrapper.call()"

### ISSUE THREAD

**Issue by ashkanee** [fabiodimarco/tf-levenberg-marquardt#22]
When executing (it is the wrapped model from [here](https://github.com/fabiodimarco/tf-levenberg-marquardt)

`model.fit(training_dataset, epochs=5)` where
`training_dataset = tf.data.Dataset.from_tensor_slices((training_input, training_output.T))`

I get:

`RuntimeError: Exception encountered when calling ModelWrapper.call().
Could not automatically infer the output shape / dtype of 'model_wrapper' (of type ModelWrapper). Either the `ModelWrapper.call()` method is incorrect, or you need to implement the `ModelWrapper.compute_output_spec() / compute_output_shape()` method. Error encountered:
Only input tensors may be passed as positional arguments. The following argument value should be passed as a keyword argument: None (of type <class 'NoneType'>)
Arguments received by ModelWrapper.call():
  • args=('<KerasTensor shape=(None,), dtype=float32, sparse=None, name=keras_tensor_10>',)
  • kwargs={'mask': 'None'}`
  
  This happens even with the two examples provided in this repository.
  Can you please help?  Thanks

**Comment by guidosassaroli** [comment]
I get the same Error

**Comment by fabiodimarco** [comment]
Hi @ashkanee, @Hd-Edison, @guidosassaroli ,
sorry for the delay in the reply. The problem is caused by the new version of Tensorflow.

Downgrading Tensorflow to version 2.15.0 solves the issue.

`pip install tensorflow==2.15.0`
