### ISSUE TITLE
Input matrix is not invertible

### ISSUE THREAD

**Issue by Lipi2018** [fabiodimarco/tf-levenberg-marquardt#4]
Hi,

I am trying to build a regression network using levenberg optimizer. I tried using your package but I get the error - Input matrix is not invertible. Could you please suggest what I can do to resolve this error?

Thanks,
Lipi

**Comment by fabiodimarco** [comment]
Hi,

I'm sorry for the late reply. You can try in two ways:
1. Use a more stable solver `solve_method='qr'` (if you aren't already using it by default).
2. Increase the `min_value` parameter of the `DampingAlgorithm`.

The `compile` function let you specify `solve_method` and `damping_algorithm`:
```
model_wrapper.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=1.0),
    loss=lm.MeanSquaredError(),
    damping_algorithm=DampingAlgorithm(min_value=1e-6),
    solve_method='qr')
```
`min_value=1e-6` should be a safe value, of course convergence speed is likely to be slowed down.

Let me know if this works for you.
