### ISSUE TITLE
Combine fireTS library for NARX network with Levenberg Marquardt

### ISSUE THREAD

**Issue by TobiasEl** [fabiodimarco/tf-levenberg-marquardt#5]
Hi.
I want to create a NARX (Nonlinear Autoregressive with exogenous variables) model based on LM (Levenberg Marquardt) method.

Since this two methods are not implemented in keras, I search for the library fireTs [https://pypi.org/project/fireTS/](url) (for NARX) and your implementation of LM and I'm trying to combine them. This is the code:

> import tensorflow as tf
> import numpy as np
> import levenberg_marquardt as lm
> from fireTS.models import NARX
> 
> input_size = 20000
> batch_size = 1000
> 
> x_train = np.linspace(-1, 1, input_size, dtype=np.float64)
> y_train = np.sinc(10 * x_train)
> 
> x_train = tf.expand_dims(tf.cast(x_train, tf.float32), axis=-1)
> y_train = tf.expand_dims(tf.cast(y_train, tf.float32), axis=-1)
> 
> train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train))
> train_dataset = train_dataset.shuffle(input_size)
> train_dataset = train_dataset.batch(batch_size).cache()
> train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)
> 
> model = tf.keras.Sequential([
>     tf.keras.layers.Dense(20, activation='tanh', input_shape=(1,)),
>     tf.keras.layers.Dense(1, activation='linear')])
> 
> model.compile(
>     optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
>     loss=tf.keras.losses.MeanSquaredError())
> 
> model_wrapper = lm.ModelWrapper(model)
> 
> model_wrapper.compile(
>     optimizer=tf.keras.optimizers.SGD(learning_rate=1.0),
>     loss=lm.MeanSquaredError())
> 
> mdl1 = NARX(
>     model_wrapper,
>     auto_order=2,
>     exog_order=[2, 2],
>     exog_delay=[1, 1])
> 
> mdl1.fit(train_dataset,epoch=10)
> ypred1 = mdl1.predict(x=x_test, y=y_test)
> 
> ypred1

And I'm having this error:

> AttributeError                            Traceback (most recent call last)
> 
> <ipython-input-14-2e4104dcada1> in <module>()
>      37     auto_order=2,
>      38     exog_order=[2, 2],
> ---> 39     exog_delay=[1, 1])
>      40 
>      41 mdl1.fit(train_dataset,epoch=10)
> 
> 2 frames
> 
> /usr/local/lib/python3.7/dist-packages/fireTS/core.py in __init__(self, base_estimator, **base_params)
>      14 
>      15     def __init__(self, base_estimator, **base_params):
> ---> 16         self.base_estimator = base_estimator.set_params(**base_params)
>      17 
>      18     def set_params(self, **params):
> 
> AttributeError: 'ModelWrapper' object has no attribute 'set_params'

Any solution?

**Comment by TobiasEl** [comment]
Hi.
I need to create a NARX method (based on your LM). Do you know some implememtation of NARX with keras to use your LM?

**Comment by fabiodimarco** [comment]
In the above code you created a Narx class instance (which has never been used) and then you replaced it with a feedforward neural network with wrong input shape.
Based on the code in the stackoverflow comment here is a version using LM trainer:

```
import tensorflow as tf
import numpy as np
import levenberg_marquardt as lm

num_previous_steps = 8

# input data generation
numTsSamples = 1000

# time series to learn from
y = np.random.random((numTsSamples + num_previous_steps + 1,))
x = np.random.random((numTsSamples,))  # exogenous input

# creation of tapped delay
data = [np.roll(y, -i)[:numTsSamples] for i in range(num_previous_steps, -1, -1)]
data = [x] + data

# training data
data = np.stack(data, axis=1)

# expected results
y_next = y[num_previous_steps: -1]

# model training
model = tf.keras.Sequential([
    tf.keras.layers.Dense(20, activation='tanh',
                          input_shape=(num_previous_steps + 2,)),
    tf.keras.layers.Dense(1, activation='linear')])

# build the model
_ = model(data)

model_wrapper = lm.ModelWrapper(model)
model_wrapper.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=1.0),
    loss=lm.MeanSquaredError())

model_wrapper.fit(data, y_next, epochs=10)

out = model.predict(data)

```
The code that you provided is just a feedforward neural network where the input data are organized to form a NARX model.
It is missing the main part of NARX, which is the autoregressive output prediction.

**Comment by TobiasEl** [comment]
Thank you so much for helping me.

> It is missing the main part of NARX, which is the autoregressive output prediction.

I have never work with NARX, so I don't really know how to implement it, just searching code or libreries. I don't know how to specify that autoregressive output.
