### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by nicejava** [fabiodimarco/tf-levenberg-marquardt#7]
How to prediction of trainer ?

thank you

**Comment by fabiodimarco** [comment]
Hi,
I did not understand the question. Are you using the Model Wrapper class?
In that case you can do prediction both on the ModelWrapper or on the original model itself.
The Trainer class is just for training the model, if you are using it the prediction have to be done on the model after you trained it.

Did I answer the question? Let me know.

**Comment by nicejava** [comment]
Yes, i try call trainer success so when after trained variable trainer not
have method prediction ( if i use wrapper model it’s have method predict
but instance class trainer not have method predict after trainer is trained
finish , you understand my question ? .. thank you

เมื่อ ศ. 10 ก.ย. 2564 เวลา 21:18 Fabio Di Marco ***@***.***>
เขียนว่า:

**Comment by fabiodimarco** [comment]
Ok, I am glad it helped. I suggest you to use ModelWrapper instead of Trainer class though.

**Comment by nicejava** [comment]
I understand. Thank you very much.

เมื่อ ศ. 10 ก.ย. 2564 เวลา 21:27 Fabio Di Marco ***@***.***>
เขียนว่า:
