### ISSUE TITLE
Error in resuduals when labels given as int instead of float64

### ISSUE THREAD

**Issue by andreagr** [fabiodimarco/tf-levenberg-marquardt#9]
When trying to train a simple neural network with labels fed as integers I encountered the following error

`TypeError: Exception encountered when calling layer "tf.math.subtract" (type TFOpLambda).
Input 'y' of 'Sub' Op has type float32 that does not match type int64 of argument 'x'.`

Originating in the following method:

`    
def residuals(self, y_true, y_pred):
        return y_true - y_pred
`

I tried casting in the method but It raised a further error. It started working once I simply converted the labels to floats before training.

Maybe we could add a check and a warning in order to avoid runtime exceptions.

**Comment by fabiodimarco** [comment]
Hi Andrea,

thanks for the tip, I'll take a look to it. I have to check what keras does in this situation, probably it just casts the input to float32/float64 (based on tf.keras.backend.floatx() setting) without giving any assert.
